spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/test
        driver-class-name: org.h2.Driver
        username: jimin
    mvc:
        view:
            prefix: /WEB-INF/
            suffix: .jsp
    jpa:
        hibernate:
            ddl-auto: create
            show-sql: 'true'
        properties:
            hibernate:
                format_sql: 'true'

