spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/test
        driver-class-name: org.h2.Driver
        username: jimin
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://tulip-database1.c8maqvqboyme.ap-northeast-2.rds.amazonaws.com:3306/week5
#        username: admin
#        password: rejin0421
    mvc:
        view:
            prefix: /WEB-INF/
            suffix: .jsp
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: 'true'
        properties:
            hibernate:
                format_sql: 'true'

