spring:
  datasource: jdbc
  url: jdbc:mysql://wit-database-1.cnasbbajy1da.ap-northeast-2.rds.amazonaws.com::3306/wit-database-1
  username: admin
  password: witdatabasepw

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'


