spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #    datasource:
  #        url: jdbc:h2:tcp://localhost/~/test
  #        driver-class-name: org.h2.Driver
  #        username: jimin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
      url: jdbc:h2:tcp://localhost/~/test;NON_KEYWORDS=USER
      driver-class-name: org.h2.Driver
      username: jimin
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://wit-backend-practice.cpadiqsprb8b.ap-northeast-2.rds.amazonaws.com:3306/week8
#    username: admin
#    password: rejin0421
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
    show-sql:
      true

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400